### ISSUE TITLE
PV's that are not auto-provisioned are not backed up

### ISSUE THREAD

**Issue by JorritSalverda** [miracle2k/k8s-snapshots#1]
In code I see you check if a volume is actually a GCE PD.

If it's auto-provisioned the `pv.kubernetes.io/provisioned-by` annotation is present, like this:

```
"annotations": {
  "kubernetes.io/createdby": "gce-pd-dynamic-provisioner",
  "pv.kubernetes.io/bound-by-controller": "yes",
  "pv.kubernetes.io/provisioned-by": "kubernetes.io/gce-pd",
  "volume.beta.kubernetes.io/storage-class": "fast"
}
```

However if you create the PV yourself with a manifest it's not, it would look something like this:

```
"annotations": {
  "backup.kubernetes.io/deltas": "1h 8h 2d 7d 30d",
  "kubectl.kubernetes.io/last-applied-configuration": "..."
}
```

As a workaround I could obviously add the annotations myself, but isn't there another way to detect whether it's a GCE PD? Besides it doesn't feel particularly safe to add one of those GCE PV controller annotations to my 'manually' created PV.

**Comment by miracle2k** [comment]
I suppose we should just check if the PersistentVolume has a `gcePersistentDisk` in it's spec dict.  Seems a more reliable solution all around.

**Comment by bluecamel** [comment]
I added a PR that uses StorageClass to figure out the provisioner (https://github.com/miracle2k/k8s-snapshots/pull/3).  It's not perfect, but it works as long as you have StorageClass and PersistentVolume configured correctly.  Let me know what you think.
