### ISSUE TITLE
/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py:31> severity=ERROR

### ISSUE THREAD

**Issue by sztyopu** [miracle2k/k8s-snapshots#105]
Hello! We want to use **k8s-snapshot** the **GKE** cluster, our Kubernetes version 1.18, but not work.
The logs in the k8s-snapshots pod has the following error message:

> 2021-07-20T05:59:47.828323Z foreign                        [asyncio] message=Exception in callback combine.<locals>.cb(<Task cancell...cutils.py:21>>) at /usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py:31
> handle: <Handle combine.<locals>.cb(<Task cancell...cutils.py:21>>) at /usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py:31> severity=ERROR
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
>     self._callback(*self._args)
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py", line 32, in cb
>     if task.exception():
> concurrent.futures._base.CancelledError
> 2021-07-20T05:59:47.829122Z Unhandled exception in main task [k8s_snapshots.__main__] loop=<_UnixSelectorEventLoop running=False closed=False debug=False> main_task=<Task finished coro=<daemon() done, defined at /usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/core.py:585> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)> message=Unhandled exception in main task severity=ERROR
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/__main__.py", line 58, in main
>     loop.run_until_complete(main_task)
>   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
>     return future.result()
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/core.py", line 610, in daemon
>     await asyncio.gather(*tasks)
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/core.py", line 534, in scheduler
>     async for schedule in watch_schedule(ctx, snapshot_reload_trigger):
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/core.py", line 507, in watch_schedule
>     async for item in combined:
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py", line 58, in combine_latest
>     async for value in combine(**generators):
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py", line 50, in combine
>     await asyncio.gather(*tasks)
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py", line 22, in listen_and_forward
>     async for value in generator:
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/snapshot.py", line 339, in get_snapshots
>     yield await load_snapshots(ctx, backends)
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/snapshot.py", line 349, in load_snapshots
>     snapshot_results = await asyncio.gather(*tasks)
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py", line 12, in run_in_executor
>     return await asyncio.get_event_loop().run_in_executor(None, func)
>   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/snapshot.py", line 346, in <lambda>
>     lambda: backend.load_snapshots(ctx, snapshot_label_filters)
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/backends/google.py", line 179, in load_snapshots
>     snapshots = get_gcloud(ctx).snapshots()
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/backends/google.py", line 375, in get_gcloud
>     keyfile = json.loads(ctx.config.get('google_application_credentials'))
>   File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2021-07-20T05:59:47.832522Z Shutdown complete              [k8s_snapshots.__main__] message=Shutdown complete severity=INFO
> Traceback (most recent call last):
>   File "/usr/local/bin/k8s-snapshots", line 11, in <module>
>     load_entry_point('k8s-snapshots==0.0.0', 'console_scripts', 'k8s-snapshots')()
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/__main__.py", line 58, in main
>   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
>     return future.result()
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/core.py", line 610, in daemon
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/core.py", line 534, in scheduler
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/core.py", line 507, in watch_schedule
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py", line 58, in combine_latest
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py", line 50, in combine
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py", line 22, in listen_and_forward
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/snapshot.py", line 339, in get_snapshots
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/snapshot.py", line 349, in load_snapshots
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/asyncutils.py", line 12, in run_in_executor
>   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/snapshot.py", line 346, in <lambda>
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/backends/google.py", line 179, in load_snapshots
>   File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/backends/google.py", line 375, in get_gcloud
>   File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 

Pleae, help me!

**Comment by miracle2k** [comment]
I am thinking this means that GOOGLE_APPLICATION_CREDENTIALS is not set to a valid value?

**Comment by sztyopu** [comment]
Yes. Thank you! 
The GOOGLE_APPLICATION_CREDENTIALS I set the file path. 
I deleted this env and set the 
GCLOUD_CREDENTIALS_FILE=/root/.config/gcloud/application_default_credentials.json
Now work.
Thanks for some great work!
