### ISSUE TITLE
Expected behavior and exclusion of PersistentVolumes

### ISSUE THREAD

**Issue by envintus** [miracle2k/k8s-snapshots#14]
As I re-read the documentation and try this out I just wanted to nail down what the expected behavior of PV snapshots should be.

Right now I see the following:
- PV's without an annotation will have an initial snapshot created, but no additional snapshots and therefore no aging/expiration
- PV's with a defined annotation will create and expire subsequent snapshots based on the delta rule

Pretty simple, but I'm looking for clarification, because my initial impression after reading the documentation is that the k8s-snapshots pod _**would only**_ create snapshots for PV's that do have the annotation with a defined delta. If I'm wrong and what I described above is the correct behavior then I feel like the documentation should be clearer.

Also, is there any way to exclude PV's from having snapshots created all together?

**Comment by miracle2k** [comment]
The behaviour described in the documentation is the desired behaviour. Only pv's that have the annotation should be considered, all others ignored.

Are you sure this is what you are seeing? What does the log say? 

I would be a strange bug indeed if volumes that don't have the annotation are processed.

**Comment by miracle2k** [comment]
Actually, looking at the code, I think the behaviour you describe is possible and was introduced by accident when we started to check the claim refs for annotations.

It should be fixed in master via #11, but that one is not released yet.

**Comment by envintus** [comment]
@miracle2k thanks for responding. Yes, #11 will be great. We actually built a Docker image from that forked repo's branch and it works like a charm. Any idea on when you may cut another release?

**Comment by miracle2k** [comment]
There is a v0.2 tag now on docker hub.
