### ISSUE TITLE
Support an interface for third parties to add snapshot support

### ISSUE THREAD

**Issue by govint** [miracle2k/k8s-snapshots#25]
Add an interface for CRUD of snapshots so third parties can add support for the PVs they support on their storage.

**Comment by miracle2k** [comment]
You want a browser-based UI that can add the annotations, do I understand correctly?

**Comment by govint** [comment]
No, I mean an interface at the backend so different storage providers can plugin their support for snapshots.

**Comment by miracle2k** [comment]
I see. This is in progress right now, as I am adding an AWS backend.

**Comment by miracle2k** [comment]
latest now has AWS and Google Cloud backends.
