### ISSUE TITLE
Sometimes a duplicate snapshot is created

### ISSUE THREAD

**Issue by miracle2k** [miracle2k/k8s-snapshots#28]
As best as I ca tell from the log:

- While a snapshot is running, the scheduling coroutine schedules it again (due to a duplicate update from the rule generator).
- After the first snapshot is completed, the second one is started right way, without the scheduler running again, with the newly created one being considered in the plan this time around.

**Comment by dcaschutz** [comment]
Same here, except it runs continually generating new snapshots.

**Comment by dcaschutz** [comment]
This appears to be fixed in the latest "dev" image.

**Comment by timstoop** [comment]
Same for me, testing the dev image now.

**Comment by timstoop** [comment]
I have that same behaviour with the dev image :(

**Comment by timstoop** [comment]
@miracle2k How can I best help with debugging that issue?

**Comment by timstoop** [comment]
It looks like it's doing this because the snapshot is taking too long to finish...
