### ISSUE TITLE
Question about PING_URL Functionality

### ISSUE THREAD

**Issue by sudermanjr** [miracle2k/k8s-snapshots#40]
Hi,

First of all, this project is great.  Nice and simple and seems to work without issue.

The PING_URL seems to work fine, but I was thinking about how it works and it raised an eyebrow.  If there's only one PING_URL for the entire deployment, then it will ping for every single snapshot that is taken.  This could mean that a single PV/PVC was never backed up, but your watcher, like deadmanssnitch would never know this, because it would be receiving pings from other snapshots.

Am I missing something, or is this the case?

Regards,
Andrew

**Comment by miracle2k** [comment]
Sorry that I missed responding to this. It's as you describe. My purpose was to just ensure the daemon is running and creating backups, and I didn't want to setup a separate watcher for every volume. However, for those that do, it might make sense to extend the feature.
