### ISSUE TITLE
Investigate: Load more than the AWS snapshot limit

### ISSUE THREAD

**Issue by shanegibbs** [miracle2k/k8s-snapshots#52]
We are running the `k8s-snapshots:v2.0` container in GKE.

After a while, we start getting a snapshot every minute and our container gets stuck in a crash loop. After deleting all the snapshots and starting again, it works as expected for a while and then starts crash looping again.

From what I can tell, the following happens:

1. Once we reach a certain threshold of snapshots (turns out to be ~500), snapshots start happening more frequent than has been specified.
2. The more snapshots we have, the worse it gets. We reach a point where we get a new snapshot every minute.
3. We eventually reach our quota limit for snapshots.
4. When `k8s-snapshots` creates a snapshot, the GCP `operation` is flagged as complete, but when the app requests the snapshot info from GCP, it doesn't exist (due to quota limits). This causes a 404 error and crashes the app.

After a bit of digging, I put together a fix that seems to work for us: https://github.com/miracle2k/k8s-snapshots/pull/51

**Comment by miracle2k** [comment]
Leaving this open to investigate the related issue on AWS.

**Comment by shanegibbs** [comment]
Thanks @miracle2k :) Do you think you will do a new container build after looking into the AWS issue?

**Comment by miracle2k** [comment]
It seems that AWS does not have a result limit, miraculously: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSnapshots.html

I did myself saw it return 2k snapshots, so that seems like a good sign.
