### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by andrewhowdencom** [miracle2k/k8s-snapshots#6]
I built a helm chart for this. Do you want it in:

- This repo
- The https://github.com/kubernetes/charts repo

I can submit a PR against either. The latter is my preferred choice, as it's becoming kind of a canonical "please look for charts here" type thing.

**Comment by miracle2k** [comment]
The latter seems more sensible to me too.

**Comment by andrewhowdencom** [comment]
Closed in favour of https://github.com/kubernetes/charts/issues/783

**Comment by eh-am** [comment]
What was the conclusion here? Both issues are closed and I couldn't find the chart there. Am I missing something?

**Comment by andrewhowdencom** [comment]
Hola @eh-am; 

Helm closes issues that are stale. TBH I haven't had a change to push this change
