### ISSUE TITLE
how to restore from a snapshot on a google pv?

### ISSUE THREAD

**Issue by dirtbag** [miracle2k/k8s-snapshots#65]
Whats the suggested way to restore the snapshots?  I found the docs at 
https://cloud.google.com/compute/docs/disks/restore-and-delete-snapshots#restoresnapshotlargersize
but was wondering if there was a more simple way of doing it?

regards,
db

**Comment by joshorig** [comment]
Hi, @dirtbag did you find an answer to this?

**Comment by dirtbag** [comment]
yeah i finally did it using the info posted above..
