### ISSUE TITLE
What exact permission on EC2 and S3 is required by k8s-snapshots?

### ISSUE THREAD

**Issue by yujunz** [miracle2k/k8s-snapshots#76]
Does k8s-snapshots have a limited resource pattern and actions? 

I just don't want to grant too wide access for an automation tool.

**Comment by glesperance** [comment]
just found this https://github.com/miracle2k/k8s-snapshots/issues/54

**Comment by miracle2k** [comment]
Cool, so closing this, and hopefully we can get it into the readme.
