### ISSUE TITLE
Backup Type

### ISSUE THREAD

**Issue by ADaruka** [miracle2k/k8s-snapshots#94]
When the snapshots are taken according to the deltas, is the backup incremental or differential?
![whatis-pillar_full_incremental_differential_backup](https://user-images.githubusercontent.com/41139360/72329944-b0ca3100-36db-11ea-9b38-391101154500.png)

**Comment by miracle2k** [comment]
You'd have to look into how each cloud provider handles snapshots. I suspect that internally they use an incremental approach. 

However, from the perspective of this app, this breakdown isn't really meaningful; we only see what could be called "full backups"; that is the only thing the cloud provider exposes to us.
